# Generated by Django 3.2.9 on 2021-12-12 09:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bgc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_game',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=40),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='b_game',
            name='description',
            field=models.TextField(max_length=200),
        ),
    ]
