# Generated by Django 3.2.9 on 2021-12-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bgc', '0002_auto_20211212_1137'),
    ]

    operations = [
        migrations.AddField(
            model_name='b_game',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='b_game',
            name='description',
            field=models.TextField(),
        ),
    ]
