# Generated by Django 3.2.9 on 2021-12-12 09:49

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bgc', '0003_auto_20211212_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('stars', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)])),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('b_game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bgc.b_game')),
            ],
            options={
                'verbose_name_plural': 'reviews',
            },
        ),
    ]
